MyBanks/Bank/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

app_name = 'Bank'
urlpatterns = [
    url('bank/', views.BankListView.as_view(),name='list'),
    url('bank/<int:pk>/', views.BankDetailView.as_view(),name='detail'),
    url('branch/', views.BranchListView.as_view(),name='list'),
    url('branch/<int:pk>/', views.BranchDetailView.as_view(),name='detail'),
]

MyBanks/MyBanks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .router import router

urlpatterns = [
    url('admin/', admin.site.urls),
    url('api/',include(router.urls), name='api')
]

MyBanks/Bank/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class Banks(models.Model):
    name = models.CharField(max_length=49, blank=True, null=True)
    id = models.BigIntegerField(primary_key=True)

    def __str__(self):
        return self.name
    class Meta:
        managed = False
        db_table = 'banks'


class Branches(models.Model):
    ifsc = models.CharField(max_length=11, primary_key=True)
    bank_id = models.BigIntegerField(blank=True)
    branch = models.CharField(max_length=74, blank=True, null=True)
    address = models.CharField(max_length=195, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    district = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=26, blank=True, null=True)

    def __str__(self):
        return self.bank_id


    class Meta:
        managed = False
        db_table = 'branches'

MyBanks/Bank/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .models import Banks, Branches
from rest_framework import viewsets
from django.views.generic import ListView, DetailView
# Create your views here.


class BankListView(ListView):
    model = Banks
    template_name = 'list.html'

class BankDetailView(DetailView):
    model = Banks
    template_name = 'details.html'


class BranchListView(ListView):
    model = Branches
    template_name = 'list.html'

class BranchDetailView(DetailView):
    model = Branches
    template_name = 'details.html'


        

MyBanks/Bank/templates/details.html
{% extends 'snippets/base.html' %}

{% block title %}Snippet Detail{% endblock title %}

{% block content %}

<h1>{{ Bank.id }}</h1>

<pre>
  {{ Bank.name }}
</pre>

{% endblock content %}

MyBanks/Bank/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
  {% block content %}

  {% endblock content %}
</body>
</html>

MyBanks/Bank/templates/list.html
{%extends 'index.html' %}
{% block title %}Branch Lists{% endblock title %}

{% block content %}
<ul>
        {% for snippet in Bank_list %}
          <li>
            <a href="{% url 'Bank:detail' Bank.id %}">{{ Bank.name }}</a>
          </li>
        {% endfor %}
      </ul>
{% endblock content%}